package mikehawes.adventofcode.calendar2025.day7;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class Day7Star1Test {

    @Test
    void should_count_beam_splits() {
        String input = """
                .......S.......
                ...............
                .......^.......
                ...............
                ......^.^......
                ...............
                .....^.^.^.....
                ...............
                ....^.^...^....
                ...............
                ...^.^...^.^...
                ...............
                ..^...^.....^..
                ...............
                .^.^.^.^.^...^.
                ...............
                """;
        assertThat(Day7Star1.countBeamSplits(input))
                .isEqualTo(21);
    }
}
