package mikehawes.adventofcode.calendar2025.day7;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class Day7Star2Test {

    @Test
    void should_count_tachyon_paths() {
        String input = """
                .......S.......
                ...............
                .......^.......
                ...............
                ......^.^......
                ...............
                .....^.^.^.....
                ...............
                ....^.^...^....
                ...............
                ...^.^...^.^...
                ...............
                ..^...^.....^..
                ...............
                .^.^.^.^.^...^.
                ...............
                """;
        assertThat(Day7Star2.countTachyonPaths(input))
                .isEqualTo(40);
    }
}
